j-mnr/gophergo.dev

content/basics/constants.md
=> feat: Add lesson on constants.

content/basics/for-loop.md, content/basics/if-else.md
=> Lesson ifelse

content/basics/array.md
=> feat: Add lesson on arrays.

content/basics/slice.md
=> feat: Add lesson on slices in Go.

content/basics/range.md, content/basics/template.md
=> Lesson range

content/basics/function.md, content/basics/slice.md
=> feat: Explain unpacking slices.

content/basics/00-hello-gophers.md, content/basics/01-types.md, content/basics/02-variables.md, content/basics/03-constants.md, content/basics/04-if-else.md, content/basics/05-switch.md, content/basics/06-for-loop.md, content/basics/07-array.md, content/basics/08-slice.md, content/basics/09-map.md, content/basics/10-range.md, content/basics/11-runes.md, content/basics/12-function.md, layouts/basics/list.html, layouts/basics/single.html
=> feat: Order lessons.

content/basics/04-operators.md, content/basics/05-if-else.md, content/basics/06-switch.md, content/basics/07-for-loop.md, content/basics/08-array.md, content/basics/09-slice.md, content/basics/10-map.md, content/basics/11-range.md, content/basics/12-runes.md, content/basics/13-function.md
=> feat: Add operator lesson.

content/basics/17-interfaces.md
=> feat: Add lesson on interfaces.

content/basics/17-embed.md
=> feat: Add lesson on embedding.

content/basics/06-switch.md, content/basics/11-range.md, content/basics/14-struct.md, content/basics/17-interfaces.md, content/basics/18-embed.md, content/basics/19-error.md
=> Lesson errors

content/basics/13-function.md, content/basics/20-defer.md
=> Lesson defer

content/basics/21-panic-recover.md
=> feat: Add lesson on panic & recover

content/basics/22-closure.md
=> feat: Add lesson on closures

config.yaml, layouts/basics/list.html, layouts/basics/single.html
=> feat: Add prev and next lesson links

content/basics/03-constants.md, content/basics/05-if-else.md, content/basics/07-for-loop.md, content/basics/09-slice.md, content/basics/11-range.md, content/basics/13-function.md, content/basics/14-struct.md, content/basics/15-pointer.md, content/basics/17-interfaces.md, content/basics/19-error.md, content/basics/20-defer.md, content/basics/21-panic-recover.md
=> refactor: Switch XXX tags for NOTE

content/basics/concurrency/23-goroutine.md, content/basics/concurrency/_index.md
=> Lesson goroutine

content/basics/02-variables.md, content/basics/04-operators.md, content/basics/06-switch.md, content/basics/09-slice.md, content/basics/10-map.md, content/basics/11-range.md, content/basics/13-function.md, content/basics/14-struct.md, content/basics/17-interfaces.md, content/basics/18-embed.md, content/basics/19-error.md, content/basics/20-defer.md, content/basics/21-panic-recover.md
=> fix: Remove stutter

content/basics/01-types.md, content/basics/02-variables.md, content/basics/03-constants.md, content/basics/04-operators.md, content/basics/05-if-else.md, content/basics/06-switch.md, content/basics/07-for-loop.md, content/basics/08-array.md, content/basics/09-slice.md, content/basics/10-map.md, content/basics/11-range.md, content/basics/12-runes.md, content/basics/13-function.md, content/basics/14-struct.md, content/basics/15-pointer.md, content/basics/16-method.md, content/basics/17-interfaces.md, content/basics/18-embed.md, content/basics/19-error.md, content/basics/20-defer.md, content/basics/21-panic-recover.md, content/basics/22-closure.md, content/basics/concurrency/23-goroutine.md
=> Fix types lesson

content/basics/21-panic-recover.md, content/basics/22-closure.md, content/basics/concurrency/_index.md
=> feat: Explain closure gotcha

content/basics/02-variable.md, content/basics/03-constant.md, content/basics/09-slice.md, content/basics/13-function.md
=> fix: Singularize lessons that can be

content/basics/00-hello-gophers.md, content/basics/06-switch.md, content/basics/09-slice.md, content/basics/10-map.md, content/basics/11-range.md, content/basics/12-runes.md, content/basics/13-function.md, content/basics/15-pointer.md, content/basics/16-method.md, content/basics/18-embed.md, content/basics/19-error.md, content/basics/20-defer.md, content/basics/21-panic-recover.md, content/basics/22-closure.md, content/basics/concurrency/23-goroutine.md, content/basics/concurrency/_index.md, content/cmd/index.md, content/code/index.md, content/projects/index.md, content/std/index.md, layouts/_default/_markup/render-link.html, layouts/shortcodes/anchor-new-window.html
=> Render links defaults

assets/css/common/syntax.css, config.yaml, content/basics/04-operators.md, content/basics/20-defer.md, layouts/shortcodes/setup-instructions.md
=> Lesson enum

content/basics/06-switch.md, layouts/shortcodes/side-by-side.html
=> feat: Implement side by side code blocks; Use in switches

content/basics/03-constant.md, content/basics/09-slice.md
=> Update lesson const

content/basics/01-types.md, content/basics/02-variable.md, content/basics/03-constant.md, content/basics/04-operators.md, content/basics/05-if-else.md, content/basics/06-switch.md, content/basics/07-for-loop.md, content/basics/08-array.md, content/basics/09-slice.md, content/basics/10-map.md, content/basics/11-range.md, content/basics/12-runes.md, content/basics/13-function.md, content/basics/14-struct.md, content/basics/15-pointer.md, content/basics/16-method.md, content/basics/17-interfaces.md, content/basics/18-embed.md, content/basics/19-error.md, content/basics/20-defer.md, content/basics/21-panic-recover.md, content/basics/22-closure.md, content/basics/concurrency/23-goroutine.md, layouts/shortcodes/setup-instructions.md
=> refac: Use Shortcode for Setup in basics

content/resources/index.md, content/std/bytes/index.md, content/std/time/index.md
=> feat: Add `time` to std

content/std/_index.md, content/std/bytes.md, content/std/net_http_cookiejar.md, content/std/time.md
=> feat: Add net/http/cookiejar examples
